# Voortijdig schoolverlaten: beleidscontext en cijfers

In dit hoofdstuk bespreken we eerst de achtergrond en definitie van voortijdig schoolverlaten in Nederland (1.1.). Daarna kijken we naar de aantallen vsv’ers in Nederland en Arnhem (1.2.). We sluiten af met de aanpak van vsv, waarbij we onderscheid maken in de maatregelen op landelijk en regionaal niveau en het huidige beleid in Arnhem (1.3.).    

## Schoolverzuim en schoolverlaten
Elke jongere blijft wel eens van school weg. Bijvoorbeeld omdat iemand in de familie wordt begraven of omdat hij/zij naar het ziekenhuis moet. Dat verzuim is geoorloofd wanneer de school er toestemming voor geeft. Het kan ook zijn dat een jongere wegblijft en de school er helemaal geen toestemming voor heeft gegeven. Wanneer hij of zij afwezig is zonder toestemming praten we over ongeoorloofd verzuim en dat wordt ook wel spijbelen genoemd.    
Spijbelen zelf hoeft nog niet meteen een reden van zorg te zijn. Het kan een luxe-probleem zijn, omdat de ouders bijvoorbeeld hun kind vanwege extra vakantiedagen thuishouden. Het kan ook zijn dat er thuis problemen spelen of dat de jeugdige andere problemen heeft. Wanneer het verzuim een indicator is voor deze problemen wordt gesproken over signaalverzuim en de school is verplicht dit in de gaten te houden. Het wordt echt een probleem wanneer het verzuim langer dan vier weken duurt. Vaker of langdurig van school wegblijven kondigt niet zelden schooluitval aan. En schooluitval is vaak een voorbode van voortijdig schoolverlaten [@wagemans_2015; @theunissen_2016]    
Nederland kent een leer- en kwalificatieplicht. De leerplicht geldt in Nederland voor alle leerlingen van hun 5e jaar tot en met het schooljaar waarin een leerling 16 jaar wordt. Ouders of verzorgers van leerlingen in deze leeftijd zijn verplicht hun kinderen in te schrijven op een school. De leerplichtambtenaar controleert of een kind dat staat ingeschreven op een school ook daadwerkelijk aanwezig is. De leerplicht verloopt in het schooljaar dat de leerling 16 jaar wordt, nadat een leerling een startkwalificatie behaalt of zodra een leerling minimaal 12 volledige schooljaren onderwijs heeft genoten. Ook de jaren dat een leerling is blijven zitten of heeft overgeslagen tellen daarbij mee. De voorschoolse periode telt niet mee. 
De kwalificatieplicht geldt voor jongeren die nog geen diploma hebben behaald in het schooljaar dat ze 16 jaar oud worden. Om aan de kwalificatieplicht te voldoen moeten jongeren een startkwalificatie behalen; dit is een diploma op minimaal het niveau van havo, vwo of mbo niveau 2. Als een jongere 18 jaar wordt vervalt de kwalificatieplicht. Voor jongeren in het speciaal onderwijs geldt een uitzondering op de kwalificatieplicht.   
Jongeren hebben vaak niet door dat zij onder de kwalificatieplicht vallen vanaf hun 16e jaar omdat ze bezig zijn met een opleiding. Belangrijk verschil met leerplichtige leerlingen is dat scholieren die vallen onder de kwalificatieplicht meer eigen verantwoordelijkheid hebben om naar school te gaan (ook al is de kwalificatieplicht ingezet om de leerplicht te verlengen en zijn er juridische middelen van handhaving tot 18 jaar). Ziekmelden, aanvragen van verlof en het contact met de leerplichtambtenaar is nu hun eigen verantwoordelijkheid en ligt niet meer bij hun ouders als ze niet meer thuis wonen. 

*Voortijdig schoolverlaten*
De leer- en kwalificatieplicht geldt voor alle kinderen en jongeren in de leeftijd van 5 tot 18 jaar. Jongeren tot 23 jaar die geen startkwalificatie hebben gehaald en geen opleiding volgen, worden tot de voortijdig schoolverlaters gerekend. Uitzonderingen hierop zijn jongeren die het niveau van de startkwalificatie niet kunnen halen omdat ze lichamelijke of geestelijke beperkingen hebben. Dit zijn bijvoorbeeld jongeren die het speciaal onderwijs hebben doorlopen en afgesloten. Jongeren met een diploma op mbo niveau 1 en die minimaal 12 uur werk hebben, hoeven niet begeleid te worden om een startkwalificatie te halen [@rijksoverheid_2020].

## Vsv in Nederland en Arnhem
Het aantal voortijdig schoolverlaters is vanaf het schooljaar 2010-2011 gedaald, maar vanaf 2016-2017 wederom gestegen [@rijksoverheid_2020; @brief_2020]. Die ontwikkeling van aantallen vsv'ers is in de onderstaande figuur (Figuur 1) te zien.

FIGUUR 1

In Tabel 1 worden de landelijke streefpercentages maximale uitval voor 2018-2019 en 2019-2020 voor het voortgezet onderwijs en mbo zichtbaar gemaakt.

TABEL 1

Een aantal opleidingsroutes kent meer vsv'ers dan andere routes. Het aantal jongeren dat voortijdig uitstroomt uit een havo of vwo-opleiding is relatief klein. De afgelopen jaren bestond het grootste percentage vsv’ers uit mbo’ers die hun opleiding niet afgerond hebben (meer dan 60%). Het percentage is met name hoog op mbo niveau 1. Het aantal vmbo’ers dat voortijdig stopt of de overstap naar het mbo niet maakt is relatief klein. Deze groep vormt echter wel een kwetsbare groep op de arbeidsmarkt. Deze leerlingen komen vooral uit de vmbo-basis en -kadergerichte leerweg in vergelijking met de -gemengde en -theoretische leerweg [@herweijer_2006][^1]:Zodra een jongere de overstap maakt van vso naar mbo 1 wordt hij kwalificatieplichtig. In principe wordt er door het onderwijs een inschatting gemaakt of een jongere in staat is om vervolgonderwijs te volgen. Mocht dit niet het geval zijn dan hebben deze jongeren uitstroomprofiel arbeid of dagbesteding. Verder geldt voor jongeren die hun mbo 1 diploma halen en voor 1 oktober een contract hebben dat zij niet meetellen in de vsv-cijfers. 

### 1.2.1.	Vsv in Arnhem
In Figuur 2 is de regionale trend (in percentages) van vsv in Arnhem/Nijmegen van de afgelopen drie jaar in het vo te zien.

FIGUUR 2

In Figuur 3 zien we de regionale trend voortijdig schoolverlaten in het mbo.

FIGUUR 3

In de regio Arnhem/Nijmegen zien de percentages over 2017-2018 (laatste schooljaar waarover we gegevens in stukken vonden), volgens de voortgangsrapportage vsv van de subregio Arnhem, er als volgt uit (zie: [@gemeente_arnhem_2019]):   
-	2,12%: het percentage vsv’ers (landelijk 1,89%). Dat zijn in totaal 1.189 vsv’ers;   
-	0,42%: het percentage vsv’ers in het vo.   
-	6,35%: het percentage vsv’ers in het mbo.   
-	RMC regio Arnhem/Nijmegen neemt de 29ste plek in op de landelijke ranglijst van 39 RMC-regio’s.    

Vervolgens hebben we naar de gegevens van de gemeente Arnhem zelf gekeken voor het jaar 2017-2018. De totalen voor vsv (in aantallen en percentages) zijn weergegeven, nu voor drie verschillende leefomgevingen, van groot naar klein: met achtereenvolgens acht gebieden, 24 buurten en 98 wijken (Bijlage 1). Qua gebied van CSA, Malburgen (3,8%) en Presikhaaf (3,6%) op. Qua buurt vallen Centrum (5,3%), Spijkerkwartier (5,3), Klarendal (5,9%) en Geitenkamp (5,5%) op. En qua wijk (de kleinste eenheid waarover we gegevens kunnen terugvinden en waarbij we er ons tegelijk van bewust moeten zijn dat kleinere aantallen grotere effecten op de percentages kunnen hebben) vallen Hommelstraat (10%), Klarendal-Zuid (11,8%), Transvaalbuurt (11,8%) en Middelgraaflaan e.o. (23,3%) op. 
Voor de informatie in buurten kunnen we een uitsplitsing maken in vo en mbo. In het jaar 2017-2018 nemen 7.891 jongeren deel aan het voortgezet onderwijs. 56 jongeren worden tot de vsv’ers gerekend en dat is 0.7% van het totaal. Als we naar de uitsplitsing in 24 buurten kijken zien we dat er zeven buurten bij zijn waar geen vsv’ers wonen (bv. Centrum, Spijkerkwartier, Monnikkenhuizen, Schaarsbergen eo, Heijenoord/Lombok, Klingelbeek en Malburgen West). In vier buurten komt vsv bij meer dan een procent van de deelnemende jongeren voor (m.n. in Geitenkamp is dit percentage met 4,2% hoog). 
Het percentage vsv’ers van het mbo is aanzienlijk hoger. In Arnhem nemen 3.327 jongeren deel aan het mbo (mbo niveau 1 tot en met 4) en 259 deelnemers hebben de school verlaten. Dat is in totaal 7,8%. In acht buurten is het percentage lager dan 6%. De percentages zijn met name hoog in Klarendal (14,5%), Klingelbeek (10,0%) en Malburgen-West (12,5%), ook al moeten we voorzichtig zijn met de duiding van deze cijfers op dit niveau.


## De landelijke, regionale en stedelijke aanpak 
In deze paragraaf bespreken we kort de landelijke doelstellingen en financiering, de regionale plannen en het beleid van de gemeente Arnhem.

*Landelijke aanpak*
De Rijksoverheid heeft als doel gesteld dat er in 2024 maximaal 20.000 vsv’ers in het voortgezet onderwijs en mbo zijn. Er is 80 miljoen beschikbaar gesteld om zowel gemeenten als scholen te ondersteunen om maatregelen te nemen, bijvoorbeeld door meer aandacht te besteden aan studiekeuze en ziekteverzuim. Onlangs liet het ministerie van OCW weten dat de gedane investeringen niet tot het gewenste resultaat geleid hebben. In 2018-2019 was er zelfs een stijging naar 26.894 vsv’ers. Ten opzichte van het voorgaande jaar (2017-2018) hebben 1.046 meer jongeren het onderwijs verlaten. Van alle leerlingen en studenten (tot 23 jaar) verliet in 2017-2018 1,91% het onderwijs zonder startkwalificatie. In het jaar 2018-2019 was dat 2,01% [@brief_2020]. 
Op landelijk niveau zijn er afspraken gemaakt over de aanpak van vsv in de afspraken over passend onderwijs en het Thuiszitterspact. Het doel van passend onderwijs is dat elk kind binnen zijn of haar onderwijs carrière, ondersteuning kan krijgen als dat nodig is. Het Thuiszitterspact moet samenwerking tussen verschillende partijen faciliteren zodat jongeren niet langer dan 3 maanden thuis zitten[^2]:(https://www.nji.nl/nl/Kennis/Dossier/Voortijdig-schoolverlaten-en-verzuim/Aanpak-en-preventie). 
In Nederland wordt verder gebruik gemaakt van de Methodische aanpak Schoolverzuim (MAS). MAS geeft een systematische beschrijving van de mogelijkheden die er zijn om in te grijpen bij schoolverzuim en heeft als doel om schooluitval te voorkomen waarbij de verschillende betrokken partijen, zoals leerplichtambtenaar en wijkteams, met elkaar samenwerken. Vanuit de MAS is er een sterke inzet ter voorkoming van de route naar strafrecht en wordt groot belang gehecht aan het vrijwillig kader. De regio Arnhem is daar sterk op gericht [^3]:(https://www.ingrado.nl/onderwerp/methodische_aanpak_schoolverzuim_mas).

*De regionale aanpak*
De aanpak van vsv is Nederland regionaal georganiseerd. Sinds 2002 geldt de “Wet houdende regels inzake de Regionale Meld- en Coördinatiefunctie voortijdig schoolverlaten” (RMC-wet). Sindsdien vallen vsv’ers onder de verantwoordelijkheid van een Regionaal Meld- en Coördinatiepunt (RMC) voortijdig schoolverlaten. Deze RMC’s krijgen geld van de Rijksoverheid en hebben als doel om jongeren zonder startkwalificatie in beeld te krijgen, te registreren en hen op vrijwillige basis terug naar een opleiding of een leerwerkplek te begeleiden om jongeren alsnog een startkwalificatie te laten behalen. Zij zorgen voor regionale samenwerking tussen gemeenten, (onderwijs)instellingen en organisaties die werkzaam zijn op het terrein van arbeidsvoorziening, onderwijs, jeugdhulpverlening en welzijn. RMC’s hebben als doel om voor alle jongeren tot 23 jaar de meest passende en hoogst haalbare onderwijs of arbeidsmarktpositie te organiseren.[^4]:(https://www.ingrado.nl/onderwerp/wat_is_rmc)  In Nederland zijn er 39 RMC regio’s waarover alle gemeenten verdeeld zijn. Arnhem behoort tot de regio Arnhem/Nijmegen waarbinnen ook een aantal kleinere gemeenten vallen. In de praktijk is de samenwerking tussen gemeenten en onderwijsinstellingen georganiseerd in een subregio Arnhem en een subregio Nijmegen [@gemeente_arnhem_2019]. Voor de periode 2016-2020 heeft de regio de volgende doelen gesteld: (1) meer jongeren in de regio kunnen een startkwalificatie halen; (2) meer jongeren in een kwetsbare positie de schoolloopbaan kunnen volgen die recht doet aan hun capaciteiten; en (3) voor deze jongeren de aansluiting op werk wordt verbeterd. Deze doelen zijn vertaald in een aantal maatregelen, namelijk:    
-	het geven van extra ondersteuning aan overbelaste jongeren in het voortgezet onderwijs en mbo;    
-	verdere ontwikkeling van loopbaanoriëntatie en -begeleiding in het voortgezet onderwijs;   
-	jongeren bij de overgang naar mbo in beeld houden en waar nodig bij hun opleidingskeuze ondersteunen;   
-	verzuimaanpak voor jongeren zonder startkwalificatie tussen 18 en 23 jaar;   
-	het verzorgen van een extra voorbereidings- en nazorgprogramma voor jongeren die qua capaciteit naar het mbo kunnen, maar bij wie vanwege specifieke belemmeringen het risico op uitval groot is (pro/vso);   
-	ondersteunen van jongeren in een kwetsbare positie bij de overgang naar werk.     
De uitwerking van deze maatregelen is te lezen in ‘School en werk: elke jongere een passende route’.[^5]:(https://www.rblmidden-gelre.nl/l/library/download/urn:uuid:4e49a329-db49-43d3-b6ad-c6601e8a16c4/regionaal+vsv-programma+2017-2020+subregio+arnhem.pdf). Voor de uitvoering van deze lijnen ligt de verantwoordelijkheid deels bij het onderwijs en deels bij de medewerkers van het RMC. In de praktijk opereren Arnhem en Nijmegen al jaren gescheiden in goed overleg. Vanaf 2021 worden het twee zelfstandige regio’s.

*De aanpak in Arnhem*
Het laatste plan van aanpak voor voortijdig schoolverlaten van de gemeente Arnhem is van 2016 [@gemeente_arnhem_2016]. De nadruk werd toen gelegd op de structurele ondersteuning in de leefomgeving van jongeren. Wanneer jongeren op school zitten is vooral het onderwijs aan zet. Hier gaat het om het bieden van goed en aantrekkelijk onderwijs met ondersteuning vanuit verschillende terreinen (waaronder jeugdhulp via sociale wijkteams, jeugdgezondheidszorg en leerplicht). Dit beleid zou voor een beter doorlopende schoolloopbaan moeten zorgen. Één plan van aanpak dat alle complexe problemen uit de weg ruimt, zo wordt verondersteld, bestaat niet. Een aanpak vanuit verschillende kanten zou meer geschikt zijn. Voor de aanpak van voortijdige schooluitval wordt gekozen voor een structurele en continue inzet van menskracht en middelen op een aantal gebieden tegelijkertijd. Daarbij wordt er samengewerkt tussen de gemeente Arnhem, scholen, hulpverleningsinstellingen en het Regionaal Bureau Leerlingzaken Midden-Gelre (RBL). Op verschillende terreinen van het lokaal beleid (jeugdhulpverlening, participatie en wijkteams) komt het voortijdig schoolverlaten (vsv) terug. 
De gemeente Arnhem heeft in samenspraak met onder andere het onderwijsveld, wijkteams en diverse andere partners in Arnhem een vijftal speerpunten opgesteld [^6]:[@gemeente_arnhem_2016]. Plan van aanpak voortijdig schoolverlaten Arnhem. Gemeente Arnhem.,  namelijk:   
-	Vergroten ouderbetrokkenheid (waarbij ervan uit wordt gegaan dat als ouders betrokken zijn bij de schoolloopbaan van hun kinderen dit een gunstige uitwerking heeft op hen op welke leeftijd dan ook);   
-	Intensiveren aanpak schoolziekteverzuim (met inzet van medische expertise en de overtuiging dat snelle interventies en direct reageren de beste resultaten opleveren);   
-	Versterken jeugdhulp in en om de school (van belang nu de verantwoordelijkheid daarvoor sinds 2015 bij de gemeente zelf ligt);    
-	Extra begeleiding jongeren naar school en/of werk (door onder andere mentoring door ondernemers, individueel begeleiden van jongeren die in het mbo uitvallen en door het creëren van werkervaringsplekken);   
-	Outreachende en laagdrempelige aanpak (met name voor jongeren die geen motivatie (meer) hebben voor leren, of om regulier te werken of een uitkering aan te vragen).    








