# Wat is bekend over vsv uit de (internationale) literatuur

Nadat we de cijfers en de beleidscontext van vsv met betrekking tot Arnhem in kaart hebben gebracht, hebben we de (inter)nationale literatuur erop nageslagen. Arnhem heeft namelijk de ambitie om de impact van haar preventieve inzet op het voorkomen van voortijdig schoolverlaten te vergroten. Om dat reëel te maken is inzicht nodig in de oorzaken van voortijdig schoolverlaten waar de preventieve inzet op gericht kan worden. Hiervoor hebben we een literatuuronderzoek naar voortijdig schoolverlaten en interventies uitgezet. Over de resultaten daarvan doen we in dit hoofdstuk verslag en geven we een samenvatting van de gevonden literatuur. We starten met een beschrijving van hoe we de informatie verzameld hebben (2.1). Daarna besteden we aandacht aan wat er bekend is uit internationale literatuur over de oorzaken van voortijdig schoolverlaten (2.2). Vervolgens besteden we aandacht aan het onderzoek naar de effectiviteit van interventies op dit gebied, zowel internationaal als nationaal (2.3). We sluiten dit hoofdstuk af met een conclusie (2.4).     


## Zoekstrategie

In verschillende zoekmachines (zoals Scopus, Web of Science en Google Scholar) en respositories (Cochrane Liberary. Campbell Collaboration) hebben we gezocht naar artikelen. We hebben zoektermen gebruikt als: *School dropout, early school leaving, absenteeism*, en *truancy*. We hebben ons gericht op reviews en meta-analyses. In deze artikelen worden conclusies getrokken op basis van verschillende studies, waardoor deze artikelen meer informatie geven dan individuele onderzoeken. Daarnaast hebben we gebruik gemaakt van de zogenaamde ‘snowball’ methode. Dat betekent dat we in gevonden artikelen gekeken hebben naar referenties waarnaar verwezen wordt en deze artikelen ook geïncludeerd hebben. We hebben enkele uitsluitingscriteria gehanteerd. Zo hebben we alleen artikelen gepubliceerd na 2000 geïncludeerd en alleen gekeken naar (wetenschappelijke) artikelen (en geen hoofdstukken van boeken etc.). Tot slot hebben we alleen Engelstalig en Nederlandse artikelen geïncludeerd. 
In de volgende paragrafen staan de resultaten van deze zoektocht. Het betreft geen systematische literatuurzoektocht waarin alle gepubliceerde literatuur terugkomt. Ons doel is om hier op een bondige en overzichtelijke manier de hoofdlijnen van de literatuur weer te geven. 

*Verschillende definities* 
In Nederland is de definitie van voortijdig schoolverlaten ‘Voortijdig schoolverlaters zijn jongeren tot 23 jaar die het onderwijs verlaten zonder startkwalificatie (diploma havo, vwo of mbo niveau 2)’. In internationale literatuur worden andere definities gehanteerd, maar de kern blijft dat jongeren het onderwijs verlaten zonder dat ze een bepaald minimaal diploma gehaald hebben, vaak van het voortgezet onderwijs (De Witte et al, 2013). 

## Meerdere factoren op meerdere levensdomeinen 

Als jongeren stoppen met onderwijs zonder dat jongeren hun startkwalificatie hebben gehaald, worden ze benoemd als voortijdig schoolverlater. Vaak komt het stoppen met een opleiding niet uit het niets, maar zijn er al eerdere signalen van leerlingen die perioden niet aanwezig zijn. Onderzoek en beleidsmaatregelen over dit onderwerp kijken daarom vaak breder, bijvoorbeeld naar zowel schoolverzuim als voortijdig schoolverlaten. Kearney (2008) beschouwt schoolverlaten als een continuüm van ‘zeggen niet naar school te willen gaan’ tot ‘complete afwezigheid van school voor een langere periode’. 
Alle meta-analyses en review studies verwijzen naar meerdere (levens)domeinen en factoren die een rol spelen. In dit hoofdstuk maken we onderscheid in individuele-, familie -, school-, en omgevingsfactoren. In de meeste artikelen wordt er een opsomming van risicofactoren gegeven, terwijl nog weinig bekend is over de interactie tussen factoren van diverse levensdomeinen (Ripamonti, 2018). Daarnaast zijn veel studies correlationeel (op hetzelfde tijdsmoment gekeken naar samenhang) in plaats van longitudinaal (over een langere periode) waardoor het onmogelijk is om uitspraken te doen over causaliteit (wat veroorzaakt wat). 

**Individuele factoren** 
Op het individuele niveau wordt vaak gekeken naar de relatie met prestaties op school. Voorspellers zijn bijvoorbeeld een negatieve houding ten opzichte van school en een slechte relatie met de leerkracht (Gubbels et al., 2019) Qua prestaties is een daling van academische prestaties een risicofactor, maar vooral blijven zitten lijkt een belangrijke factor om school permanent te verlaten (De Witte et al., 2013). Maar ook de betrokkenheid bij school, oftewel de aanwezigheid en inzet van leerlingen, heeft een relatie met voortijdig schooluitval. 
Melkevik et al. (2016) hebben een meta-analyse gedaan om te kijken naar de relatie tussen internaliserende problemen (zoals angst en depressie) en voortijdig schoolverlaten. Ze concluderen dat de kans kleiner is dat jongeren met internaliserende problematiek hun voortgezet onderwijs afronden in vergelijking met jongeren zonder problematiek. De reden waarom dat zo is, is echter onduidelijk, omdat de relatie deels of volledig veroorzaakt lijkt te worden door comorbide externaliserende problemen, zoals gedragsproblemen of ADHD. Gakh et al. (2020) bevestigen in hun literatuurreview dat de afwezigheid van school en middelengebruik met elkaar samenhangen, maar dat de richting van de relatie onduidelijk is (zorgt middelengebruik voor meer afwezigheid op school of zorgt afwezigheid op school voor meer middelengebruik?). Ook Townsend et al. (2007) bevestigen de relatie tussen middelengebruik (alcohol, roken, marihuana en andere drugs) en voortijdig schoolverlaten, maar ze noemen ook enkele beperkingen van de onderzoeken en vragen aandacht voor meer focus op longitudinaal onderzoek. Hetzelfde geldt voor spijbelen, vsv en delinquent gedrag. De correlatie tussen beide wordt herhaaldelijk gevonden, maar het zou kunnen dat vsv en delinquent gedrag door dezelfde onderliggende factoren veroorzaakt wordt en daarom schijnaar gerelateerd zijn (Weerman & van der Laan, 2006). 
Hoewel externaliserende problematiek gerelateerd is aan schoolverzuim, speelt het volgens de analyse van Gubbels et al. (2019) geen rol bij voortijdig schoolverlaten. Ook lichamelijke aandoeningen, zoals astma, zijn gerelateerd aan schoolverzuim (Kearney, 2018) en voortijdig schoolverlaten (De Witte et al., 2013). 

**Familiefactoren** 
De invloed van sociaal-economische status (ses) wordt als een van de belangrijkste factoren beschouwd die samenhangen met vsv (De Witte et al., 2013). Ses wordt vaak geoperationaliseerd door te kijken naar het opleidingsniveau van de ouders. Als ouders lager opgeleid zijn, is de kans groter dat kinderen uitvallen op school. Bovendien wordt een lage betrokkenheid van ouders bij school vaak genoemd als risicofactor. Maar ook als ouders weinig ondersteuning bieden, of juist weinig controlerend zijn, kunnen dit risicofactoren zijn voor schoolverzuim en uitval (Gubbels et al. 2019).

**Schoolfactoren** 
Bij schoolfactoren wordt onder andere gewezen op het sociale en academische klimaat op school. Een positief klimaat is gecorreleerd met lagere percentages voortijdig schoolverlaten (Kearney, 2018). Dat wordt onder andere gemeten door te kijken naar een hoge aanwezigheid van leerlingen op school en of disciplinemaatregelen als rechtvaardig worden gezien (De Witte et al., 2013). Maar ook een hoge kwaliteit van de leerkrachten en de lessen op school, verminderen de kans op hoge vsv-percentages (De Witte et al., 2013). Tot slot worden in sommige studies karakteristieken van school, zoals grote klassen en scholen genoemd als risicofactor (Gubbels et al. 2019). Terwijl andere auteurs aangeven dat dit geen direct effect heeft, maar deze karakteristieken zorgen voor een negatief schoolklimaat dat wel een risicofactor voor vsv is (De Witte et al., 2013). 

**Omgevingsfactoren** 
In de bredere omgeving rondom leerlingen wordt vooral gewezen op de omstandigheden in de wijk en de rol van vrienden. Als vrienden gericht zijn op het afronden van een opleiding, kunnen ze de kans op schoolverlaten verminderen, terwijl als leerlingen vrienden hebben die zelf school hebben verlaten, dit juist de kans op schoolverlaten vergroot. Maar ook als er bijvoorbeeld weinig betaald werk te vinden is omdat er sprake is van een hoge werkloosheid, zal dit de kans op voortijdig schoolverlaten verminderen (De Witte et al., 2013). 

**Beschermende factoren**
Naast risicofactoren, kunnen we ook kijken naar factoren die gerelateerd zijn aan de betrokkenheid bij school (e.g. schoolengagement) en de kans op het afronden van het onderwijs met een diploma vergroten. Er is minder onderzoek naar betrokkenheid bij school gedaan in vergelijking met studies naar schoolverzuim en voortijdig schoolverlaten. Deels komen de factoren die invloed hebben op schoolverlaten overeen met de factoren die invloed hebben op schoolbetrokkenheid. Oftewel, betrokkenheid van ouders bij school, goede relatie met de leerkracht, positief schoolklimaat, maar ook deelname aan programma’s in de gemeenschap (wijk, buurt) zijn positief geassocieerd met het behalen van een diploma. Op individueel niveau zijn daarnaast ook intrinsieke motivatie, betrokkenheid en participatie op school, vertrouwen in hun eigen prestaties en het perspectief dat je het zelf in de hand hebt, genoemd (Zaff et al., 2017). 

## Interventies  

We hebben de informatie over interventies ingedeeld in internationale onderzoeken en nationale onderzoeken. In de internationale literatuur hebben we onderscheid gemaakt in interventies die zich specifiek richten op (factoren die gerelateerd zijn aan) voortijdig schoolverlaten en preventieve aanpakken. In de nationale onderzoeken kijken we naar het landelijk beleid en repressieve interventies. 

**Internationale interventies gericht op aanpak vsv**
In een meta-analyse is gekeken naar programma’s die erop gericht zijn om voortijdig schoolverlaten te verminderen. Zij hebben zich gericht op school en omgevingsprogramma’s en vonden van 177 studies (152 algemeen en 15 voor zwangere jongeren) dat er geen verschil in effectiviteit was tussen verschillende programma’s. Zij trekken de conclusie dat programma’s in het algemeen effectief zijn als ze juist worden geïmplementeerd en geschikt zijn voor de omgeving (Wilson et al., 2010). Maynard en collega’s (2012) hebben een overzicht gemaakt van studies die zich richten op schoolverzuim en komen tot een soortgelijke conclusie. Over het algemeen hebben de programma’s een positief effect op jongeren, gemiddeld zijn ze 4.7 dagen meer op school aanwezig dan de controle groep jongeren die geen programma gevolgd hebben. Maar ook zij vinden geen verschil tussen de effecten van verschillende programma’s. 
Ekstrand (2015) heeft op basis van 155 studies een opiniërend artikel geschreven hoe zij denkt dat kinderen op school zullen blijven. Zij concludeert dat er een verandering plaats moeten vinden in de focus van interventieprogramma’s waarbij ze zich niet moeten richten op het individu maar meer op de school en de omgeving. Ook is ze er voorstander van om in te zetten op onder andere het creëren van een positief schoolklimaat, waarmee ze aangeeft meer in te willen zetten op beschermende factoren om de betrokkenheid bij school te vergroten. 
Kearney (2019) pleit ervoor om op de aanpak van vroegtijdig schoolverlaten meer multi-dimensioneel in te richten. Waarbij wordt ingezet op drie niveaus: (1) factoren die de aanwezigheid op school bevorderen, (2) reacties op eerste signalen en afwezigheid van school en (3) ernstig schoolverzuim. Hij geeft aan dat zijn model er op gericht is om de heterogeniteit te laten zien, zowel in interventies, risicofactoren als verschillende gradaties van verzuim.  
Tot slot, zijn er vergelijkingen gemaakt tussen de literatuur naar dit onderwerp en onderzoek naar de effecten van praktijk- en beleidsinterventies. De auteurs concluderen dat de meeste interventies zich richten op een bepaalde factor of individuele aanpak, terwijl uit de literatuur bekend is dat meerdere risicofactoren een rol spelen en interventies vroeg zouden moeten worden ingezet (Freeman & Simonsen, 2015). Ook andere auteurs pleiten voor het includeren van meerdere factoren om effectieve interventies te creëren (Gonzales-Rodriquez en al., 2019). 

**Preventieve interventies**
Theunissen-Lamers (2016) beschrijft in haar proefschrift dat schoolverlaten– net als andere problemen in de adolescentie en vroeg-volwassenheid – zelden iets is dat van de een op de andere dag ontstaat, omdat het veelal een dynamisch proces is en al eerder in het leven begint (zie Figuur 4). Vaak is het een proces dat zich ontwikkelt van een normale situatie, naar signalen, naar problemen, naar stoornissen, die pas over langere tijd zichtbaar worden. Het is daarom allicht beter om naar de onderliggende oorzaken te kijken waarvan we weten dat deze tot problemen en stoornissen kunnen leiden en daar vroegtijdig op te investeren. Ook bij schoolverlaten is het nodig dat je meer oog krijgt voor dit graduele en complexe proces dat veelal aan vroegtijdig schoolverlaten grondslag ligt.

HIER EEN PLAATJE, FIGUUR 4

Daarnaast is er veel onderzoek gedaan naar algemene preventieprogramma’s, waarbij breed ingezet wordt op risico- en beschermende factoren op verschillende niveaus (individu, school, omgeving, etc). In een programma als Communities that Care (CtC) wordt op wijkniveau ingezet op het tegengaan van probleemgedrag bij jongeren te verminderen, waarbij schooluitval ook wordt meegenomen. In Nederlands onderzoek bleek dat de samenwerking tussen verschillende partijen verbeterd is, maar dat jongeren niet minder probleemgedrag vertoonden (Steketee et al., 2012). 

**Onderzoek naar Nederlandse aanpakken** 
Vanuit het WODC is onderzoek gedaan naar justitiële interventies voor schoolverzuim. In 2007 zijn de programma’s, Halt, Roos en Ouders Present, onderzocht en werd geconcludeerd dat ze niet effectief zijn in het terugdringen van schoolverzuim. De deelnemers zijn wel tevreden over de programma’s. Ook zijn het programma’s die zich breed inzetten en ook aan aspecten als opvoeding aandacht besteden en daar zouden ze goede resultaten kunnen behalen (Van Burik et al, 2007). Daarnaast is gekeken naar de werkzame elementen van de Halt behandeling op basis van wetenschappelijke litera¬tuur. Voor verschillende elementen is ondersteuning gevonden in de literatuur als ze wel aan bepaalde voorwaarden voldoen. Als voorbeeld: het element excuus aanbieden is alleen werkzaam als een jongere oprecht is in zijn/haar excuses en zich schuldig voelt (Buysse et al., 2017).
Tot slot, is er gekeken naar de effectiviteit van beleidsmaatregelen in Nederland op zowel het individuele niveau als het schoolniveau (De Witte & Cabus, 2013). Beleidsmaatregelen lopen vaak tegelijkertijd, waardoor het lastig is om zicht te krijgen op het effect van individuele maatregelen. De meeste onderzochte maatregelen hebben een negatief effect op het voortijdig schoolverlaten, dus ze zorgen voor minder vsv’ers. Echter hebben (van de onderzochte maatregelen) alleen ‘mentoring en coaching’, ‘optimal track profession’ en ‘dual track’ een significant negatief effect. Bovendien laat het onderzoek zien dat vooral scholen met een relatief hoog percentage vsv’ers profiteren van de maatregelen in vergelijking met scholen waar een laag percentage vsv’ers naartoe gaan.  

## Conclusie
Alle auteurs zijn het erover eens dat vsv niet door één factor veroorzaakt wordt, maar dat meerdere factoren op verschillende levensgebieden een rol spelen. Over het algemeen wordt gekeken naar de domeinen: individu, familie, school en omgeving. Op dit moment is er nog weinig onderzoek gedaan naar de relatieve bijdrage van de bepaalde factoren (i.e. spelen vrienden een belangrijkere rol dan familie). Het is de vraag in hoeverre het mogelijk is om hier op individueel niveau uitspraken over te doen. Voor sommige leerlingen zullen depressieve klachten de doorslag geven, terwijl voor een andere jongere het schoolklimaat een grotere rol speelt. Het is wel bekend dat hoe meer risicofactoren een jongere heeft, hoe groter de kans is op negatieve uitkomsten (Farrington et al., 2020). Ook op het gebied van interventies zijn verschillende programma’s onderzocht die effectief zijn in het verminderen van schoolverzuim, maar waarbij het niet duidelijk is welke factoren een interventie onderscheidend maken. Oftewel, de belangrijkste boodschap is dat voor het voorkomen en ingrijpen bij vsv naar meerdere domeinen (individu, familie, school, omgeving) gekeken moet worden en dat interventies die integraal werken en ook aandacht besteden aan school en de (familie)omgeving daarom succesvoller zullen zijn in de aanpak van vsv dan interventies die zich alleen richten op het individu. 






