# Het toekomstig beleid

## Discussiebijeenkomst
Op basis van onze bevindingen (zoals beschreven in hoofdstuk 1 t/m 3) hebben we met enkele betrokkenen bij het vsv-beleid van Arnhem van gedachten gewisseld over de vraag wat dit betekent voor de toekomstige vsv-inzet in Arnhem. Vanwege de coronacrisis vond de bijeenkomst digitaal plaats. De discussie vond plaats op 23 april 2020 en de volgende personen deden mee: Paul Winters, Ien Kigge en Marthe Mittendorff (Gemeente Arnhem), Jos Gipmans (stafmedewerker studentzaken Rijn IJssel), Marith Berntsen (RBL beleidsmedewerker), Nanette Zwiers (Coördinator RMC Regio Arnhem). In de discussie ging het vooral om de vraag hoe het toekomstige beleid een betere bijdrage kan leveren aan het terugdringen van voortijdig schoolverlaten en het ondersteunen van jongeren in kwetsbare posities. Met het onderzoek en de dialoog met verschillende stakeholders willen we een basis voor een aangepast toetsingskader voorleggen dat kan worden gebruikt bij de beoordeling van vsv-subsidieaanvragen in de toekomst.
Tijdens de bijeenkomsten stonden een drietal discussiepunten centraal: 

>1. Waar moet het vsv-beleid op gericht worden? Richt dat vsv-beleid zich op specifieke doelgroepen of op alle leerlingen die mogelijk uitvallen? Is het gericht op het verlagen van het percentage vsv'ers of zou het ingezet moeten worden op jongeren in kwetsbare positie? Als ergens voor wordt gekozen; wat valt dan af van de huidige subsidies en wordt dat geambieerd?

Tijdens de bijeenkomst wordt vastgesteld dat het vsv-beleid uit veel losstaande initiatieven bestaat en dat dit op regionaal niveau ook het geval is. Op regionaal niveau wordt gezocht naar een meer integrale aanpak en meer samenwerking. Dit zou voor het lokale plan ook goed zijn. Daarnaast zou er een meer cijfermatige keuze kunnen worden gemaakt, waarbij meer gekeken wordt naar waar er winst te behalen is en waar vsv meer voorkomt (bijvoorbeeld een bepaalde doelgroep of bepaalde wijken). Projecten kunnen nog steeds een preventieve insteek hebben als wordt gekeken naar bij welke doelgroep vsv vooral voorkomt en hoe daar goed voortijdig op is in te grijpen. De uitval op mbo niveau 1 is groot en is voor veel jongeren het eindstation. Mogelijk kan voornamelijk op deze groep ingezet worden. Het is ook een optie om naar studierichtingen te kijken waar overstappen over het algemeen meer tijd kost en waar jongeren langer buiten een schoolomgeving staan.
Een ander idee dat naar voren werd gebracht is dat bij de aanvraag voor subsidie al veel winst te behalen is, bijvoorbeeld door te vragen op welk gebied men winst wil behalen en hoe men jongeren wil helpen. Het zou goed zijn als men zich van de eigen rol bewust is. Er moet meer afbakening zijn van de doelgroep en het beoogde effect van het project. Daarnaast is het nodig om naar de evaluatie van resultaten te vragen, ook tussentijds. Oftewel, in de aanvraag zou al over monitoring en evaluatie nagedacht moeten worden. Ook samenwerking met anderen zou in de aanvraag aan bod kunnen komen. Net als in het rapport van de Rekenkamer dat recent is uitgekomen voor de gemeente Arnhem, kan de nadruk worden gelegd op netwerksamenwerking en niet op ketensamenwerking. Projecten moeten zich bewust zijn van de eigen verantwoordelijkheid. Als iedereen dat doet, kan men er later op teruggrijpen. Niet alleen de aanvrager maar ook de subsidiegever weet op deze manier goed waar men naar kijkt. Bij de beoordeling is het bovendien ook goed als er jongeren zelf direct bij betrokken zijn.

Het is volgens de aanwezigen bij de discussiebijeenkomst ook goed om naar het niveau van kwetsbaarheid bij jongeren te kijken. Soms zijn er jongeren die uitvallen maar waar je niet zoveel zorgen over hoeft te maken. Op mbo niveau 1 en 2 zitten kwetsbare jongeren waarbij uitval wel een grote invloed heeft. Kwetsbaarheid doet zich daar op meerdere terreinen voor en die context speelt een rol. Ook de leerlingen van de ISK zijn over het algemeen kwetsbaarder.
Bij schoolverlaten zijn overstappen en transitiepunten volgens de aanwezigen heel belangrijk, omdat veel leerlingen daar uitvallen. Het onderwijs moet zich niet alleen focussen op het behalen van een diploma, maar zich ook richten op de arbeidsmarkt. Daarom is het ook goed jongeren over langere tijd te begeleiden (vmbo, mbo en arbeid), waarbij betrouwbare contacten langdurig bij de jongere betrokken zijn (vo-mbo-arbeidsmarkt). Maar de vraag is volgens de aanwezigen of je hier winst mee behaalt in vsv, want het grootste deel van degenen die hier uitvallen, wordt geen echte vsv’er. 

>2. Nu worden allemaal losse subsidies verstrekt en projecten uitgezet. Hoe kan het vsv-beleid meer integraal vsv-beleid worden en er voor zorgen dat er meer wordt samengewerkt. Dat het beleid zich meer richt op het geheel van school, thuis en omgeving maar ook dat er meer samenwerking en afstemming is met andere betrokken organisaties (onderwijsinstellingen, RBL, maatschappelijke organisaties ed). Hoe kan ervoor worden gezorgd dat er meer aan dezelfde opgave wordt gewerkt? Hoe kan daarop worden gestuurd? 

Van verschillende kanten wordt vastgesteld dat uiteenlopende domeinen niet los van elkaar te zien zijn. Een aanpak alleen op school richten is vaak niet voldoende. Bij echte vsv’ers speelt problematiek zich niet alleen in de schoolcontext af, maar ook thuis en in de vrijetijdsomgeving van de jongere. Het is de vraag hoe de thuis- en vrijetijdsomgeving in het vsv-beleid meegenomen kunnen worden, want het is lastig om wijkteams, jeugdzorg en anderen bij het vsv-beleid te betrekken. Bovendien speelt de gezinsomgeving in het mbo niet zo, omdat deze jongeren vaak uit huis zijn, maar de buitenschoolse context speelt hier wel. Aangezien vsv samenhangt met school, moet er in de projecten volgens de aanwezigen in ieder geval een relatie zijn met school. Als je met de thuissituatie en buitenschoolse context rekening houdt, ben je als project succesvoller. 
Integraal werken wordt door de aanwezigen ondersteund, maar men vraagt zich af wat er over integraal werken in de aanpak van vsv is op te nemen. In ieder geval is er veel overlap in het aanbod van de 17 projecten en moeten zij aansluiting bij elkaar zoeken. Bovendien moet bij deze partijen tussen de oren komen dat ze verantwoordelijk zijn voor een jongere en dat zij ervoor moeten zorgen dat een jongere de hulp krijgt die het nodig heeft. De projecten moeten jongere niet weg laten gaan zonder dat ze weten waar de jongere heen gaat en daar goed aankomt.

Wat betekent dit voor het geheel en is dat meer als netwerk te benaderen? Vastgesteld wordt dat sommige partijen vooral voor zichzelf lijken te werken en niet zozeer vanuit netwerksamenwerking. De koppeling tussen de activiteiten van verschillende partijen wordt belangrijk gevonden. Aan partijen kan gevraagd worden met welke andere partijen ze willen samenwerken en op wat voor een manier. Onderwijs zou daarbij altijd een van de partijen moeten zijn. Als er op een school meer problematiek blijkt, dan moet een school ook voor hulp zorgen op dat moment. 
Onderlinge uitwisseling tussen partijen, bijvoorbeeld twee keer per jaar, zou goed zijn. Partijen zijn vaak intern gericht en zijn met eigen voortgang en overleven bezig. Maar dat is ook te verwachten omdat ze vaak onzeker zijn over hun voortbestaan. In het regionaal programma is kennisoverdracht en kennisborging verplicht, zodat het beklijft en niet persoonsafhankelijk zijn. Dit zou ook in het lokale plan verplicht kunnen worden.
De verbinding, het delen en samenwerken kan beginnen door het nieuwe lokale plan te delen. Aan het einde van het jaar wordt een bijeenkomst georganiseerd met alle partijen, zodat ze elkaar leren kennen en het nieuwe lokale plan met een groot publiek gedeeld kan worden waarbij ook jongeren uitgenodigd worden.

>3. Waaraan moeten toekomstige subsidieaanvragen voldoen? Hoe is te borgen dat in de toekomst meer projecten worden gefinancierd die op een integrale manier aan het probleem werken? Helpen duidelijke toetsingscriteria? Bijvoorbeeld een hele directe bijdrage leveren aan de doelgroep potentiële vsv’ers (m.n. vmbo, mbo niveau 1 en 2) of meer een sterke integrale aanpak (school, thuis, omgeving en samenwerking met andere organisaties)?

Bij voorgaande discussiepunten had de discussiegroep al enkele toetsingscriteria voor de toekomst met elkaar gedefinieerd. De aanvragen zouden op de volgende vragen een antwoord kunnen geven:   
-	Wat is de bijdrage aan het totale netwerk?   
-	Waarop is de aanvraag gericht (welke doelen en welk beoogd effect)?   
-	Wat is de plaats van monitoring en evaluatie in de aanvraag?
-	Hoe gaat men met transitiemomenten om?   
-	Hoe draagt men bij aan langdurige en duurzame hulp (niet loslaten van jongeren)?   

Waar valt nog meer aan te denken? Gesteld wordt dat de eigen verantwoordelijkheid van de aanvrager van belang is. Hoe geeft hij/zij dat vorm? Houding, gedrag en verantwoordelijkheidsniveau zijn lastig om in een subsidieregeling om te zetten en als voorwaarde te stellen, maar de verwachting kan wel worden geschept. Hier zit ook monitoring en evaluatie aan vast van de gemeente. Het is volgens de aanwezigen verstandig als gemeente te weten wanneer ze tevreden is. Dat kan alleen als ze weet wat ze wil en dit helder en smart is geformuleerd. Dat er nu goed over wordt nagedacht, is al winst. Laat de aanvrager ook vooral reflecteren op wat ze wil en welke rol en positie ze daarin heeft. En ook hier wordt aangegeven dat jongeren zelf mee moeten denken over de aanvragen.
Het moet volgens de aanwezigen verplicht worden gesteld dat ze zich richten op meerdere leefgebieden en dat ze moeten samenwerken met anderen. School zou altijd terug moeten komen. Het valt ook op dat er veel projecten in het po zijn, en het is de vraag of die in de toekomst nog subsidie vanuit het vsv-beleid moeten krijgen. Het is niet vanzelfsprekend dat de gemeente projecten in het basisonderwijs subsidiëren vanuit vsv. 

## Tot slot: Een aantal zaken samengebracht
Vsv blijft een punt van aandacht in Nederland. Ondanks de investeringen vanuit de Rijksoverheid, is het aantal vsv’ers in het afgelopen jaar gestegen. Zowel op landelijk, regionaal als stedelijk niveau zijn er aanpakken te onderscheiden. Uit de literatuur is bekend dat vsv niet veroorzaakt wordt door een factor, maar verschillende levensdomeinen, zoals school en familie, een rol spelen. Toch lijken de meeste interventies zich vooral op een of twee factoren te richten. Ook de projecten die door de gemeente Arnhem gefinancierd worden, hebben niet altijd een integrale aanpak of samenwerking met andere organisaties. Uit de discussiebijeenkomst kwam naar voren dat de school als centrale speler een rol zou moeten hebben en daarnaast breder gekeken zou moeten worden. Hierbij moet aandacht zijn voor monitoring en doelen moeten gericht zijn op het terugdringen van vsv. 
